single_joint_controllers:
  
  joint_state_update: #In general for all joints
    type: joint_state_controller/JointStateController
    publish_rate: 50 #50 Hz
  
  # position controller
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 1.0, d: 1.0, i_clamp_min: -130.0, i_clamp_max: 130.0, antiwindup: True}